#! /bin/bash
if [ -e /etc/httpd/conf/httpd. conf ]; then
  exit 0
yum -y install mod_ssl
systemctl start httpd
sed -i 's/^/#/g' /etc/httpd/conf.d/welcome.conf
echo "<html><body><h1> Hi there NT1300 </h1><body><html>" > /var/www/html/index.html
systemctl restart httpd
